repos:
  # - repo: https://github.com/pre-commit/pre-commit-hooks
  #   rev: v4.4.0
  #   hooks:
  #   -   id: check-added-large-files
  #   -   id: check-toml
  #   -   id: check-yaml
  #       args:
  #       -   --unsafe
  #   -   id: end-of-file-fixer
  #   -   id: trailing-whitespace
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.254
    hooks:
    -   id: ruff
        args:
        - --fix
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
