version: "3"

tasks:
  build:
    cmds:
      - hatch build

  test:
    cmds:
      - hatch run test

  test:all:
    cmds:
      - hatch run test-adsapi

  test:watch:
    cmds:
      - fd . './' | entr -c task test

  fmt:
    ignore_error: true
    cmds:
      - ruff --fix src
      - black src
      - isort src

  check:
    ignore_error: true
    cmds:
      - ruff src/adsctl
      - black src --check
      - isort src --check-only
      # - mypy  # :)

  lockfiles:
    cmds:
      - pip-compile -q --resolver=backtracking --no-annotate --no-header -o requirements/pyproject.txt pyproject.toml --extra=test
      - pip-compile -q --resolver=backtracking --no-annotate --no-header -o requirements/linting.txt requirements/linting.in
