name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: test-${{ github.head_ref }}
  cancel-in-progress: true

env:
  PYTHONUNBUFFERED: 1
  FORCE_COLOR: 1

jobs:
  run:
    name: py ${{ matrix.python-version }}

    strategy:
      fail-fast: false
      matrix:
        # os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.10", "3.11"]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: arduino/setup-task@v1

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install rye
        run: cargo install --git https://github.com/mitsuhiko/rye rye

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/cache@v3
        id: cached-python-env
        with:
          path: ${{ env.pythonLocation }}
          key: >
            python-test
            ${{ runner.os }}
            python-${{ matrix.python-version }}
            ${{ hashFiles('pyproject.toml') }}
            ${{ hashFiles('requirements.lock') }}
            ${{ hashFiles('requirements-devlock') }}

      - name: Install dependencies
        if: steps.cached-python-env.outputs.cache-hit != 'true'
        run: |
          pip install -r requirements-dev.lock

      - name: Print Python info
        run: |
          which python
          python --version
          which pip
          pip --version
          pip freeze

      - name: Build Python package
        run: task build

      - name: Run tests
        run: hatch run cov
